require('settings')
require('mappings')
require('packer-config')
require('colorschemes-config.nightfox')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.cmp-config')
require('lualine-config')
require('treesitter-config')
require('null-ls-config')
require('lsp-config.mason-config')

